version: '3'
services:
  db:
    image: mysql:5.6.49
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data

  web:
    build: .
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /L-MGMT/config/unicorn.conf.rb 
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db
