version: '3'
services:
  db:
    image: mysql:5.6.49
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

  web:
    build: .
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 81:80
    restart: always 
    depends_on:
      - web 
