version: '3'
services:
  db:
    image: mysql:5.6.49
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"

  web:
    build: .
    command: bash -c "rm -fR tmp/pids/* ; bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db
