version: '3'
services:
  db:
    image: mysql:5.6.49
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data

  web:
    build: .
    command: /bin/bash -c "nginx && bundle exec unicorn -c config/unicorn.rb -D && while true; tail -f /dev/null"
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db
